[package]
name = "start-storage"
version = "0.1.0"
edition = "2024"
description = "Start Storage is storage system for StartDB."
authors = ["Leon Farafonov <me@leofaraf.com>"]
license = "MIT"


[dependencies]
memmap2 = "0.9.5"
